version: '3.8'

services:
  # --- INGRESS (REVERSE PROXY) ---
  ingress:
    image: nginx:alpine
    container_name: remaster_ingress
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./infrastructure/nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - app
      - keycloak

  # --- AUTHENTIFICATION ---
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: remaster_keycloak
    restart: unless-stopped
    command: start-dev --hostname-strict=false --http-enabled=true --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: auth.${DOMAIN}
      KC_PROXY_HEADERS: xforwarded
    volumes:
      - ./infrastructure/keycloak/import:/opt/keycloak/data/import
    depends_on:
      - db_keycloak

  # --- APPLICATION SKILLS HUB ---
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: remaster_app
    restart: unless-stopped
    depends_on:
      - db
      - keycloak
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DOMAIN=${DOMAIN}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      # URL Interne pour la validation des tokens (Evite le 504)
      - KEYCLOAK_INTERNAL_URL=http://keycloak:8080
    volumes:
      - ./backend/app:/app/app
      - ../apps/api/app/data:/app/app/data_source

  # --- BASES DE DONNÉES ---
  db:
    image: postgres:15-alpine
    container_name: remaster_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/init-keycloak.sql:/docker-entrypoint-initdb.d/init-keycloak.sql

  db_keycloak:
    image: postgres:15-alpine
    container_name: remaster_db_keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  keycloak_db_data:
